FROM nlundin08/devcontainers-dfdc:latest

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    apt-transport-https \
    dotnet-sdk-5.0